Repository LigeroSmart/ligerosmart, pull requests merged in 2021-05, with the labels that each got.

#57 avoid error messages in console
  Kernel/System/Console/Command/Admin/Ligero/Elasticsearch/MappingInstall.pm
Labels: bug, nextrelease

#58 Feat/issue 48 ticket log viewed history
  Kernel/Config/Files/XML/Ticket.xml
  Kernel/Modules/AgentTicketZoom.pm
  Kernel/System/Ticket.pm
  scripts/database/migrations/20210502123707_TicketViewedHistoryType.xml
Labels: nextrelease

#69 variable test before update
  var/httpd/htdocs/js/Core.AJAX.js
Labels: help wanted, nextrelease

#71 Fix Escalation Update Time Issue
  Kernel/System/Ticket/TicketExtensionsStopEscalation.pm
Labels: nextrelease

#67 Update PublicTicket.xml
  Kernel/Config/Files/XML/PublicTicket.xml
Labels: nextrelease

#66 Fix/accounted time js size
  var/httpd/htdocs/js/Core.AccountedTime.Validate.js
  var/httpd/htdocs/js/Core.AccountedTime.ValidateOneDay.js
Labels: nextrelease
