Repository LigeroSmart/ligerosmart, pull requests merged in 2021-06, with the labels that each got.

#82 Fix customer search
  Kernel/Modules/CustomerTicketSearch.pm
  Kernel/System/Ticket/Event/NotificationEvent/Transport/SmsNotify.pm
Labels: nextrelease

#81 Feat/apidoc
  Kernel/GenericInterface/Operation/Admin/Generic.pm
  Kernel/GenericInterface/Operation/ConfigItem/ConfigItemCreate.pm
  Kernel/GenericInterface/Operation/ConfigItem/ConfigItemDelete.pm
  Kernel/GenericInterface/Operation/ConfigItem/ConfigItemGet.pm
  Kernel/GenericInterface/Operation/ConfigItem/ConfigItemSearch.pm
  Kernel/GenericInterface/Operation/ConfigItem/ConfigItemUpdate.pm
  Kernel/GenericInterface/Operation/FAQ/LanguageList.pm
  Kernel/GenericInterface/Operation/FAQ/PublicCategoryList.pm
  Kernel/GenericInterface/Operation/FAQ/PublicFAQGet.pm
  Kernel/GenericInterface/Operation/FAQ/PublicFAQSearch.pm
  Kernel/GenericInterface/Operation/GeneralCatalogLigero/GeneralCatalogGetValues.pm
  Kernel/GenericInterface/Operation/Ligero/LigeroEasyConnector.pm
  Kernel/GenericInterface/Operation/LigeroSmart/Search.pm
  Kernel/GenericInterface/Operation/MiscLigero/LinkObject.pm
  Kernel/GenericInterface/Operation/MiscLigero/SurveySearch.pm
  Kernel/GenericInterface/Operation/MiscLigero/SurveyVote.pm
  Kernel/GenericInterface/Operation/Session/SessionCreate.pm
  Kernel/GenericInterface/Operation/Session/SessionGet.pm
  Kernel/GenericInterface/Operation/Ticket/TicketCreate.pm
  Kernel/GenericInterface/Operation/Ticket/TicketGet.pm
  Kernel/GenericInterface/Operation/Ticket/TicketHistoryGet.pm
  Kernel/GenericInterface/Operation/Ticket/TicketSearch.pm
  Kernel/GenericInterface/Operation/Ticket/TicketUpdate.pm
  Kernel/GenericInterface/Operation/TicketLigero/ArticleAttachmentGet.pm
  Kernel/GenericInterface/Operation/TicketLigero/PrioritySearch.pm
  Kernel/GenericInterface/Operation/TicketLigero/QueueSearch.pm
  Kernel/GenericInterface/Operation/TicketLigero/StateSearch.pm
  Kernel/GenericInterface/Operation/TicketLigero/TicketSearch.pm
  Kernel/GenericInterface/Operation/TicketLigero/TypeSearch.pm
  apidoc.json
Labels: nextrelease

#78 show age as date
  Kernel/Config/Files/XML/Ticket.xml
  Kernel/Modules/CustomerTicketOverview.pm
  Kernel/Output/HTML/Templates/Standard/CustomerTicketOverview.tt
Labels: nextrelease, testing

#76 LigeroAPI added
  scripts/database/migrations/20210526154436_LigeroAPI.xml
  var/packagesetup/LigeroAPI.pm
Labels: nextrelease

#77 Feat/customer company enabled for profile
  Kernel/Config/Files/XML/Ticket.xml
  Kernel/Modules/CustomerTicketMessage.pm
  Kernel/Modules/CustomerTicketOverview.pm
  Kernel/Modules/CustomerTicketSearch.pm
Labels: nextrelease, testing

#79 remover servicos acl search
  Kernel/Modules/CustomerTicketMessage.pm
  Kernel/Modules/CustomerTicketSearch.pm
Labels: testing

#83 fix responsive nav conflict, solves issue #63
  var/httpd/htdocs/skins/Agent/ligero/css/Core.Default.css
Labels: nextrelease
